### ISSUE TITLE
CVSS Score Tag

### ISSUE THREAD

**Issue by tgorup** [aaanders/cvedetails-reporter#1]
In the config.json file, <code>cvsscoremin</code> should be <code>cvssscoremin</code> (missing an "s") as per JSON URL output from http://www.cvedetails.com/.

Great script though, appreciate the contribution.

**Comment by aaanders** [comment]
Wow. Feel terrible having missed your input for half a year :D 
Thanks for the contribution!

**Comment by tgorup** [comment]
Not a problem. I had it fixed on my end. Great job and it's a very nice tool for regular reports. Thanks for your time.
